export const initialCrmState = {
  calendarEvents: [
    { day: 5, label: "Villa del Sole", type: "project" },
    { day: 8, label: "Sopralluogo Tigli", type: "visit" },
    { day: 10, label: "Preventivo Alba", type: "quote" },
    { day: 12, label: "Magnolie", type: "project" },
    { day: 15, label: "Richiamo Neri", type: "call" },
    { day: 16, label: "09:30 Studio Bianchi", type: "visit" },
    { day: 16, label: "16:00 Revisione", type: "quote" },
    { day: 17, label: "Corso Italia", type: "project" },
    { day: 19, label: "Invio scale", type: "quote" },
    { day: 23, label: "Follow-up Serena", type: "call" },
    { day: 24, label: "Avvio Casa Ferri", type: "project" },
    { day: 26, label: "SAL Aurora", type: "project" },
  ],
  customers: [
    {
      id: "cust-1",
      name: "Condominio Villa del Sole",
      type: "Condominio",
      primaryContact: "Amm. Paolo Neri",
      phone: "+39 339 452 1180",
      email: "paolo.neri@example.it",
      address: "Via Roma 18, Milano",
      lastContact: "16 giugno 2026",
      status: "Cantiere attivo",
      openValue: "€ 74.000",
      projects: ["Facciata", "Ponteggi", "Tinteggiatura"],
      tags: ["Alta priorità", "SAL giugno"],
    },
    {
      id: "cust-2",
      name: "Studio Bianchi",
      type: "Azienda",
      primaryContact: "Laura Bianchi",
      phone: "+39 02 4455 9012",
      email: "studio.bianchi@example.it",
      address: "Corso Italia 42, Milano",
      lastContact: "16 giugno 2026",
      status: "Sopralluogo",
      openValue: "€ 18.500",
      projects: ["Uffici piano terra"],
      tags: ["Misure", "Preventivo"],
    },
    {
      id: "cust-3",
      name: "Sig.ra Moretti",
      type: "Privato",
      primaryContact: "Anna Moretti",
      phone: "+39 347 660 9081",
      email: "anna.moretti@example.it",
      address: "Via Verdi 7, Monza",
      lastContact: "14 giugno 2026",
      status: "Nuova richiesta",
      openValue: "€ 9.800",
      projects: ["Ristrutturazione bagno"],
      tags: ["Da fissare"],
    },
    {
      id: "cust-4",
      name: "Residenza Le Magnolie",
      type: "Condominio",
      primaryContact: "Amm. Elena Costa",
      phone: "+39 331 882 4400",
      email: "elena.costa@example.it",
      address: "Via Manzoni 31, Sesto San Giovanni",
      lastContact: "12 giugno 2026",
      status: "Cantiere attivo",
      openValue: "€ 52.000",
      projects: ["Copertura", "Lattonerie"],
      tags: ["Scadenza 7 giorni"],
    },
    {
      id: "cust-5",
      name: "Casa Ferri",
      type: "Privato",
      primaryContact: "Marco Ferri",
      phone: "+39 348 219 7702",
      email: "marco.ferri@example.it",
      address: "Via Donizetti 12, Pavia",
      lastContact: "10 giugno 2026",
      status: "Accettato",
      openValue: "€ 36.000",
      projects: ["Cappotto termico"],
      tags: ["Avvio 24 giugno"],
    },
  ],
  pipeline: [
    {
      stage: "Nuove richieste",
      count: 6,
      deals: [
        {
          title: "Condominio Villa Serena",
          subtitle: "Rifacimento facciata",
          note: "Valore stimato € 42.000",
        },
        { title: "Sig.ra Moretti", subtitle: "Ristrutturazione bagno", note: "Sopralluogo da fissare" },
      ],
    },
    {
      stage: "Sopralluogo",
      count: 5,
      deals: [
        { title: "Studio Bianchi", subtitle: "Uffici piano terra", note: "Domani alle 09:30", tone: "accent" },
        { title: "Condominio Tigli", subtitle: "Impermeabilizzazione", note: "Tecnico: Marco" },
      ],
    },
    {
      stage: "Preventivo",
      count: 8,
      deals: [
        { title: "Impresa Alba", subtitle: "Opere interne", note: "Computo in revisione" },
        {
          title: "Amministratore Neri",
          subtitle: "Scala condominiale",
          note: "Invio entro venerdì",
          tone: "accent",
        },
      ],
    },
    {
      stage: "Accettati",
      count: 3,
      deals: [
        { title: "Casa Ferri", subtitle: "Cappotto termico", note: "Avvio 24 giugno", tone: "won" },
        { title: "Condominio Aurora", subtitle: "Ripristino balconi", note: "Contratto firmato", tone: "won" },
      ],
    },
  ],
  projects: [
    { name: "Condominio Villa del Sole", work: "Facciata, ponteggi, tinteggiatura", progress: 68 },
    { name: "Residenza Le Magnolie", work: "Copertura e lattonerie", progress: 42 },
    { name: "Negozio Corso Italia", work: "Demolizioni e nuovi impianti", progress: 81 },
  ],
  tasks: [
    { label: "Caricare foto sopralluogo Villa Serena", done: false },
    { label: "Inviare computo aggiornato", done: true },
    { label: "Preparare contratto Casa Ferri", done: false },
  ],
  todayAppointments: [
    {
      id: "apt-1",
      time: "09:30",
      title: "Sopralluogo Studio Bianchi",
      detail: "Uffici piano terra, verifica pareti e misure.",
      type: "visit",
    },
    {
      id: "apt-2",
      time: "12:00",
      title: "Richiamare Amm. Neri",
      detail: "Conferma capitolato e scelta finiture scala.",
      type: "call",
    },
    {
      id: "apt-3",
      time: "16:00",
      title: "Revisione preventivo Tigli",
      detail: "Controllo impermeabilizzazione e tempi squadra.",
      type: "quote",
    },
  ],
};
